# Generated by Django 3.0.2 on 2020-01-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0002_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='intro',
            field=models.TextField(),
        ),
    ]
