# Generated by Django 3.0.2 on 2020-01-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0003_auto_20200115_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('image', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
