# Generated by Django 3.0.2 on 2020-01-15 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0004_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='images',
            new_name='image',
        ),
    ]
